(()=>{"use strict";
const D=MIND,$=s=>document.querySelector(s),K="rethink_mind_v2";
const blank={sessions:0,history:[],used:{},tabState:{},daily:null,preferences:{},version:2};
let S=load(),tab="home",A=null,T=[];
function normalize(n){n=n&&typeof n==="object"?n:{};return Object.assign({},blank,n,{sessions:Number.isFinite(+n.sessions)?Math.max(0,+n.sessions):0,used:n.used&&typeof n.used==="object"?n.used:{},history:Array.isArray(n.history)?n.history.filter(h=>h&&h.id&&h.skill&&h.title).slice(-400):[],tabState:n.tabState&&typeof n.tabState==="object"?n.tabState:{},preferences:n.preferences&&typeof n.preferences==="object"?n.preferences:{},daily:n.daily&&typeof n.daily==="object"?n.daily:null})}
function load(){try{let n=JSON.parse(localStorage.getItem(K)||"null")||JSON.parse(localStorage.getItem("rethink_mind")||"null")||blank;return normalize(n)}catch(_){return structuredClone(blank)}}
const save=()=>localStorage.setItem(K,JSON.stringify(S)),skill=id=>D.skills.find(x=>x[0]===id)?.[1]||id;
const stop=()=>{T.forEach(x=>{clearTimeout(x);clearInterval(x)});T=[]};
const today=()=>{let d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`};
function fresh(a,k,filter=()=>true){let candidates=a.map((v,i)=>({v,i})).filter(x=>filter(x.v));if(!candidates.length)candidates=a.map((v,i)=>({v,i}));let used=S.used[k]||[],pool=candidates.filter(x=>!used.includes(x.i));if(!pool.length){used=[];pool=candidates}let pick=pool[Math.floor(Math.random()*pool.length)];S.used[k]=[...used,pick.i].slice(-Math.max(1,Math.min(candidates.length-1,18)));save();return pick.v}
function level(){let w=Math.min(8,Math.floor(S.sessions/4)+1);return {week:w,stage:w<=2?1:w<=4?2:w<=6?3:4,label:w<=2?"GRUNDLAGE":w<=4?"STEUERUNG":w<=6?"FLEXIBILITÄT":"FESTIGUNG"}}
function recentIds(n=10){return S.history.slice(-n).map(h=>h.id)}
function buildPlan(){let L=level(),counts={};D.skills.forEach(s=>counts[s[0]]=S.history.slice(-30).filter(h=>h.skill===s[0]).length);let skills=D.skills.map(s=>s[0]).sort((a,b)=>counts[a]-counts[b]);let selected=[skills[0],skills[1]];while(selected.length<4){let rest=skills.filter(x=>!selected.includes(x));selected.push(rest[Math.floor(Math.random()*rest.length)])}let recent=recentIds(10);let q=selected.map(id=>{let a=D.ex.filter(e=>e[1]===id&&(!e[5]||e[5]<=L.stage)),f=a.filter(e=>!recent.includes(e[0]));let pool=f.length?f:a;return pool[Math.floor(Math.random()*pool.length)]});if(L.stage===1)q.sort((a,b)=>["reg","att","mind","img","talk"].indexOf(a[1])-["reg","att","mind","img","talk"].indexOf(b[1]));else if(L.stage>=3)q.sort(()=>Math.random()-.5);return q}
function getDailyPlan(){if(!S.daily||S.daily.date!==today()||!Array.isArray(S.daily.ids)){let q=buildPlan();S.daily={date:today(),ids:q.map(e=>e[0])};save()}let q=S.daily.ids.map(id=>D.ex.find(e=>e[0]===id)).filter(Boolean);if(q.length!==4){q=buildPlan();S.daily={date:today(),ids:q.map(e=>e[0])};save()}return q}
function estimate(q){let sec=q.reduce((n,e)=>n+(D.duration[e[3]]||55)+10,0),lo=Math.max(3,Math.floor(sec/60)),hi=Math.max(lo+1,Math.ceil(sec*1.35/60));return `CA. ${lo}–${hi} MIN`}
function rememberScroll(){let m=$("main");if(m)S.tabState[tab]={scroll:m.scrollTop};save()}
function shell(c){$("#app").innerHTML=`<div class="shell"><header><div class="brand">RETHINK. <b>MIND</b></div><button class="more" aria-label="Einstellungen">•••</button></header><main>${c}</main><nav class="tabs">${[["home","HEUTE"],["train","TRAINING"],["progress","VERLAUF"]].map(x=>`<button class="tab ${tab===x[0]?"on":""}" data-t="${x[0]}">${x[1]}</button>`).join("")}</nav></div>`;$(".more").onclick=settings;document.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>{let target=b.dataset.t;if(target===tab){S.tabState[target]={scroll:0};save();render(true)}else{rememberScroll();tab=target;render()}});requestAnimationFrame(()=>{let m=$("main");if(m)m.scrollTop=S.tabState[tab]?.scroll||0})}
function render(reset=false){stop();if(reset)S.tabState[tab]={scroll:0};if(tab==="home")home();else if(tab==="train")train();else progress()}
function home(){let q=getDailyPlan(),e=q[0],L=level();shell(`<section class="hero"><div class="eyebrow">MENTALES TRAINING · WOCHE ${L.week}/8</div><h1>Trainiere,<br>was steuerbar ist.</h1><p>Geführtes Mentaltraining. Ohne künstliche Leistungswerte. Mit systematischem Aufbau.</p></section><button class="primary" id="start">HEUTIGES TRAINING · ${estimate(q)}</button><div class="section"><div class="head"><b>Heutiger Schwerpunkt</b><span>${L.label}</span></div><div class="card"><span class="tag">${skill(e[1])}</span><strong>${e[2]}</strong><small>${e[4]}</small></div></div><div class="section stats"><div class="stat"><b>${S.sessions}</b><span>EINHEITEN</span></div><div class="stat"><b>${S.history.length}</b><span>METHODEN</span></div><div class="stat"><b>${L.week}</b><span>TRAININGSWOCHE</span></div></div>`);$("#start").onclick=()=>session(q)}
function train(){let L=level();shell(`<section class="hero"><div class="eyebrow">TRAINING · ${L.label}</div><h1>Mentale Fähigkeiten.</h1><p>Jede Methode verlangt eine konkrete mentale Handlung.</p></section><div class="grid">${D.skills.map(s=>`<button class="card sk" data-s="${s[0]}"><strong>${s[1]}</strong><small>${s[2]}</small></button>`).join("")}</div><div id="list" class="section"></div>`);document.querySelectorAll(".sk").forEach(b=>b.onclick=()=>list(b.dataset.s))}
function list(id){let L=level();$("#list").innerHTML=D.ex.filter(e=>e[1]===id).map(e=>`<button class="card ex" data-e="${e[0]}" ${e[5]>L.stage?'disabled':''}><span class="tag">${skill(id)}</span><strong>${e[2]}</strong><small>${e[5]>L.stage?`Ab Trainingsphase ${e[5]}`:e[4]}</small></button>`).join("");document.querySelectorAll(".ex:not([disabled])").forEach(b=>b.onclick=()=>start(D.ex.find(e=>e[0]===b.dataset.e)))}
function progress(){let L=level(),counts=D.skills.map(s=>[s[1],S.history.filter(h=>h.skill===s[0]).length]);shell(`<section class="hero"><div class="eyebrow">VERLAUF · WOCHE ${L.week}/8</div><h1>Konstanz statt Punktzahl.</h1><p>Die App verfolgt Training, Abdeckung und Wiederholung. Keine erfundenen Mental-Scores.</p></section><div class="stats"><div class="stat"><b>${S.sessions}</b><span>EINHEITEN</span></div><div class="stat"><b>${S.history.length}</b><span>METHODEN</span></div><div class="stat"><b>${L.label}</b><span>PHASE</span></div></div><div class="section"><div class="card"><span class="tag">ABDECKUNG</span>${counts.map(x=>`<div class="row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</div>${S.history.slice(-8).reverse().map(h=>`<div class="card"><span class="tag">${skill(h.skill)}</span><strong>${h.title}</strong><small>${new Date(h.at).toLocaleDateString("de-DE")}</small></div>`).join("")||'<div class="card"><small>Noch keine Einheit abgeschlossen.</small></div>'}</div>`)}
function frame(e,b,a="",p=0){$("#app").innerHTML=`<div class="shell full"><div class="top"><button class="back">‹</button><div class="prog"><i style="width:${p}%"></i></div></div><div class="exercise"><div class="eyebrow">${skill(e[1])}${A?.queue?` · ${A.n}/${A.total}`:""}</div><h1>${e[2]}</h1><div class="instruction">${e[4]}</div><div class="stage">${b}</div>${a?`<div class="action">${a}</div>`:""}</div></div>`;$(".back").onclick=()=>{stop();render()}}
function start(e,queue=false,next=null,n=1,total=1){stop();A={e,queue,next,n,total};let x=10;frame(e,`<div><div class="preview">${x}</div><div class="sub">Sekunden Vorbereitung</div><div class="pills"><span class="pill">LESEN</span><span class="pill">VERSTEHEN</span><span class="pill">AUTOMATISCHER BEGINN</span></div></div>`);let q=setInterval(()=>{if(--x<1){clearInterval(q);run(e)}else if($(".preview"))$(".preview").textContent=x},1000);T.push(q)}
function run(e){({scan,breath,activation,focus,anchor,shift,imagery,coping,selftalk,cue,observe,senses,accept,relax}[e[3]])(e)}
function done(e){S.history.push({id:e[0],skill:e[1],title:e[2],at:Date.now(),stage:level().stage});S.history=S.history.slice(-400);save();if(A?.queue)return A.next();frame(e,`<div class="step"><span class="tag">ABGESCHLOSSEN</span><b>Training beendet.</b><p>Die Methode wurde deinem Verlauf hinzugefügt.</p></div>`,`<button class="primary" id="d">ZURÜCK</button>`,100);$("#d").onclick=render}
function scan(e){let i=0;function go(){if(i>=D.regions.length)return done(e);frame(e,`<div><div class="region">${D.regions[i]}</div><div class="sub">Spannung wahrnehmen · nur unnötige Spannung lösen</div><div class="pills"><span class="pill">5 SEKUNDEN</span><span class="pill">${i+1}/${D.regions.length}</span></div></div>`,"",100*i/D.regions.length);i++;T.push(setTimeout(go,5000))}go()}
function breath(e){let seq=[];for(let i=0;i<5;i++)seq.push(["Einatmen",4,1.2],["Ausatmen",6,.82]);let n=0;function go(){if(n>=seq.length)return done(e);let [w,s,z]=seq[n++];frame(e,`<div><div class="breath" id="b">${w}</div><div class="sub">${s} Sekunden</div></div>`,"",100*n/seq.length);let b=$("#b");requestAnimationFrame(()=>{b.style.transition=`transform ${s}s linear`;b.style.transform=`scale(${z})`});T.push(setTimeout(go,s*1000))}go()}
function guided(e,steps){let i=0;function go(){let s=steps[i];frame(e,`<div class="step"><span class="tag">SCHRITT ${i+1}/${steps.length}</span><b>${s[0]}</b><p>${s[1]}</p></div>`,`<button class="primary" id="n">${i===steps.length-1?"ABSCHLIESSEN":"FORTFAHREN"}</button>`,100*(i+1)/steps.length);$("#n").onclick=()=>{if(++i>=steps.length)done(e);else go()}}go()}
function activation(e){guided(e,[["Aufrichten","Richte den Oberkörper auf. Stelle beide Füße stabil auf."],["Einatmen","Atme etwas kräftiger durch die Nase ein. Richte den Blick geradeaus."],["Spannung","Erzeuge für zwei Sekunden kontrollierte Ganzkörperspannung."],["Lösen","Löse einen Teil der Spannung. Behalte Haltung und Wachheit."],["Bereit","Atme normal. Richte die Aufmerksamkeit auf die nächste Handlung."]])}
function relax(e){guided(e,[["Anspannen","Spanne Hände und Unterarme für fünf Sekunden deutlich an."],["Lösen","Löse vollständig. Nimm den Unterschied wahr."],["Schultern","Ziehe die Schultern für fünf Sekunden kontrolliert an."],["Lösen","Lasse die Schultern sinken. Atme ruhig weiter."],["Gesamtbild","Vergleiche Spannung und Entspannung im ganzen Körper."]])}
function focus(e){let a=[["ENG","Richte die Aufmerksamkeit ausschließlich auf den Punkt."],["WEIT","Der Blick bleibt am Punkt. Nimm zugleich Bildschirmränder und Umgebung wahr."],["ENG","Verkleinere den Aufmerksamkeitsraum wieder auf den Punkt."],["WEIT","Halte den Blick stabil. Erweitere nur die Aufmerksamkeit."]],i=0;function go(){if(i>=a.length)return done(e);let s=a[i++];frame(e,`<div><div class="dot"></div><div class="region" style="font-size:28px;margin-top:35px">${s[0]}</div><div class="sub">${s[1]}</div></div>`,"",25*i);T.push(setTimeout(go,10000))}go()}
function anchor(e){guided(e,[["Anker","Richte die Aufmerksamkeit auf ein einziges Geräusch."],["Halten","Bleibe bei diesem Geräusch. Andere Reize dürfen vorhanden sein."],["Weiten","Nimm nun alle Geräusche wahr, ohne eines zu verfolgen."],["Zurückführen","Wähle erneut genau ein Geräusch und kehre bewusst dorthin zurück."]])}
function shift(e){let x=fresh(D.attention,"attention");guided(e,[["Innen",x[0]],["Außen",x[1]],["Wechsel","Wechsle zweimal bewusst zwischen beiden Bezugspunkten."],["Entscheiden","Wähle den Bezugspunkt, der für die nächste Handlung nützlicher ist."]])}
function imagery(e){imgflow(e,fresh(D.scenes,"scene",x=>!x[3]||x[3]<=level().stage),null)}
function coping(e){imgflow(e,fresh(D.scenes,"coping",x=>!x[3]||x[3]<=level().stage),fresh(D.dis,"dis"))}
function imgflow(e,s,d){let detail=fresh(D.imageDetails,"imgdetail"),a=[["Umgebung",s[1]],["Perspektive","Erlebe die Szene aus deiner eigenen Perspektive."],["Körper",detail],["Handlung",s[2]]];if(d)a.push(["Störung",d],["Regulation",fresh(D.regulations,"imgreg")],["Fortsetzung","Stelle dir die unmittelbar folgende Handlung präzise und kontrolliert vor."]);else a.push(["Präzisieren",fresh(D.precision,"precision")]);guided(e,a)}
function selftalk(e){branchChoice(e,fresh(D.self,"self",x=>!x[4]||x[4]<=level().stage),"self")}
function cue(e){branchChoice(e,fresh(D.cues,"cue",x=>!x[4]||x[4]<=level().stage),"cue")}
function branchChoice(e,s,key){frame(e,`<div class="choices"><div class="step"><span class="tag">SITUATION</span><p>${s[0]}</p></div>${s[1].map((x,i)=>`<button class="choice" data-i="${i}">${x}</button>`).join("")}</div>`);document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{let i=+b.dataset.i,ok=i===s[2],best=s[1][s[2]],follow=fresh(D.followups,key+"follow");frame(e,`<div class="feedback"><span class="tag">${ok?"PASSEND":"NEU AUSRICHTEN"}</span><b>${ok?best:`${best}`}</b><p>${s[3]}</p><hr><p>${follow[0]}</p></div>`,`<div class="twobtn"><button class="secondary" id="a">${follow[1]}</button><button class="primary" id="b">${follow[2]}</button></div>`,70);$("#a").onclick=()=>application(e,s,follow,false);$("#b").onclick=()=>application(e,s,follow,true)})}
function application(e,s,f,preferred){let text=preferred?f[4]:f[3];frame(e,`<div class="step"><span class="tag">ANWENDUNG</span><b>${preferred?"Handlungsnah":"Noch präziser"}</b><p>${text}</p><br><p>Sprich die passende Formulierung einmal innerlich. Verbinde sie unmittelbar mit der vorgestellten nächsten Handlung.</p></div>`,`<button class="primary" id="n">ABSCHLIESSEN</button>`,90);$("#n").onclick=()=>done(e)}
function observe(e){guided(e,[["Bemerken","Nimm den nächsten Gedanken wahr, ohne ihn zu verändern."],["Benennen","Ordne ihn knapp ein: Planung, Bewertung, Erinnerung oder Sorge."],["Distanz","Formuliere innerlich: „Ich bemerke den Gedanken …“"],["Zurückkehren","Richte die Aufmerksamkeit wieder auf Atmung und Körperkontakt."]])}
function accept(e){let x=fresh(D.acceptance,"accept");guided(e,[["Wahrnehmen",x[0]],["Raum geben",x[1]],["Nicht lösen","Lass das Empfinden für einen Moment bestehen, ohne es wegzudrücken."],["Handeln",x[2]]])}
function senses(e){guided(e,[["Sehen","Nimm drei Formen oder Konturen wahr."],["Hören","Nimm drei unterschiedliche Geräusche wahr."],["Körper","Nimm drei Kontaktpunkte deines Körpers wahr."],["Gesamtbild","Lasse alle drei Wahrnehmungsbereiche gleichzeitig bestehen."]])}
function session(q=getDailyPlan()){let i=0;function next(){if(i>=q.length){S.sessions++;S.daily=null;save();return finish()}let e=q[i];start(e,true,next,i+1,q.length);i++}next()}
function finish(){let L=level();$("#app").innerHTML=`<div class="shell"><div class="exercise"><div class="eyebrow">RETHINK. MIND · WOCHE ${L.week}/8</div><h1>Einheit abgeschlossen.</h1><div class="stage"><div class="step"><b>Training beendet.</b><p>Die nächste Einheit berücksichtigt Verlauf, Abdeckung und zuletzt verwendete Inhalte.</p></div></div><div class="action"><button class="primary" id="h">ZUR HEUTIGEN ANSICHT</button></div></div></div>`;$("#h").onclick=()=>{tab="home";render(true)}}
function settings(){$("#app").innerHTML=`<div class="shell"><div class="top"><button class="back">‹</button><b>Einstellungen</b></div><main><section class="hero"><div class="eyebrow">DATEN</div><h1>RETHINK. MIND</h1><p>Trainingsdaten bleiben lokal auf diesem Gerät.</p></section><button class="secondary" id="exp">BACKUP EXPORTIEREN</button><input id="imp" type="file" accept=".json" hidden><br><br><button class="secondary" id="res">BACKUP WIEDERHERSTELLEN</button></main></div>`;$(".back").onclick=render;$("#exp").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:"application/json"}));a.download="RETHINK.MIND-Backup.json";a.click()};$("#res").onclick=()=>$("#imp").click();$("#imp").onchange=x=>{let r=new FileReader;r.onload=()=>{try{let n=JSON.parse(r.result);if(!n||!Array.isArray(n.history))throw Error();S=normalize(n);save();render()}catch(_){alert("Sicherung konnte nicht gelesen werden.")}};if(x.target.files[0])r.readAsText(x.target.files[0])}}
document.addEventListener("gesturestart",e=>e.preventDefault(),{passive:false});document.addEventListener("dblclick",e=>e.preventDefault(),{passive:false});document.addEventListener("pointerup",e=>{if(e.clientY<=18&&!A){S.tabState[tab]={scroll:0};save();render(true)}});if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});render();
})();
