window.MIND={
skills:[["reg","Regulation","Aktivierung und Spannung gezielt beeinflussen."],["att","Aufmerksamkeit","Den Fokus bewusst ausrichten und verändern."],["img","Vorstellung","Mentale Bilder präzise und handlungsnah aufbauen."],["talk","Selbstinstruktion","Gedanken in hilfreiche Handlungsanweisungen überführen."],["mind","Achtsamkeit","Wahrnehmen, ohne jedem Gedanken folgen zu müssen."]],
ex:[
["scan","reg","Körperscan","scan","Nimm Spannung wahr. Löse nur, was du nicht benötigst."],
["down","reg","4–6-Atmung","breath","Beruhige den Atem, ohne ihn zu erzwingen."],
["activation","reg","Aktivierung","activation","Erhöhe Wachheit und Handlungsbereitschaft, ohne Hektik."],
["focus","att","Eng · Weit","focus","Der Blick bleibt am Punkt. Nur die Aufmerksamkeit verändert sich."],
["anchor","att","Aufmerksamkeitsanker","anchor","Bemerke Ablenkung und führe den Fokus bewusst zurück."],
["scene","img","Szene aufbauen","imagery","Baue ein vollständiges mentales Bild auf. Du bestimmst das Tempo."],
["coping","img","Störung bewältigen","coping","Übe auch eine gelungene Reaktion auf eine Störung."],
["self","talk","Funktionale Sprache","selftalk","Wähle die Formulierung, die unmittelbar handlungsfähig macht."],
["cue","talk","Präziser Cue","cue","Erkenne die kurze Instruktion, die zur Situation passt."],
["observe","mind","Gedanken beobachten","observe","Nimm Gedanken wahr, ohne ihnen automatisch zu folgen."],
["senses","mind","Sinneswechsel","senses","Lenke Aufmerksamkeit bewusst zwischen Wahrnehmungskanälen.",1],
["shift","att","Innen · Außen","shift","Wechsle den Aufmerksamkeitsbezug bewusst, statt ihm zu folgen.",2],
["relax","reg","Spannung · Lösung","relax","Erzeuge und löse Spannung bewusst. Nimm den Unterschied wahr.",2],
["accept","mind","Unbehagen zulassen","accept","Lass einen inneren Zustand bestehen und bleibe trotzdem handlungsfähig.",3]],
regions:["Stirn","Augen","Kiefer","Zunge","Nacken","Schultern","Oberarme","Unterarme","Hände","Brustkorb","Bauch","Gesäß","Oberschenkel","Waden","Füße"],
self:[
["Eine anspruchsvolle Aufgabe misslingt zweimal.",["Das darf nicht wieder passieren.","Ruhig. Den nächsten relevanten Schritt sauber ausführen.","Ich muss mich stärker konzentrieren."],1,"Die Formulierung richtet den Fokus auf eine kontrollierbare Handlung."],
["Deine Gedanken sind bereits beim Ergebnis.",["Nicht an das Ergebnis denken.","Zur gegenwärtigen Aufgabe. Ein Schritt nach dem anderen.","Es wird schon funktionieren."],1,"Eine konkrete Rückführung hilft mehr als ein Verbot."],
["Die Aufgabe ist schwieriger als erwartet.",["Heute bin ich nicht in Form.","Tempo ordnen. Den nächsten Schritt präzise ausführen.","Ich muss mich zusammenreißen."],1,"Die Instruktion beschreibt Verhalten statt Leistung zu bewerten."],
["Nach einem guten Beginn steigt der eigene Erwartungsdruck.",["Jetzt bloß nicht nachlassen.","Gleicher Ablauf. Gleiche Aufmerksamkeit.","Heute läuft es perfekt."],1,"Der Prozess bleibt stabil, ohne zusätzlichen Ergebnisdruck."],
["Du bemerkst deutliche innere Unruhe.",["Ich muss sofort ruhig werden.","Unruhe wahrnehmen. Atmung ordnen. Aufgabe beginnen.","Warum bin ich wieder nervös?"],1,"Der Zustand wird angenommen und mit einer steuerbaren Handlung verbunden."],
["Du zweifelst kurz vor einer anspruchsvollen Aufgabe.",["Ich darf nicht zweifeln.","Zweifel ist da. Haltung ordnen. Ersten Schritt ausführen.","Ich muss mir mehr vertrauen."],1,"Die Formulierung trennt den inneren Zustand von der nächsten Handlung."],
["Du ärgerst dich über eine ungenaue Ausführung.",["So etwas darf mir nicht passieren.","Information nehmen. Korrektur wählen. Neu ausführen.","Vergiss den Fehler einfach."],1,"Der Fehler wird als Information genutzt, ohne ihn weiter zu bewerten."],
["Du fühlst dich müde und interpretierst das sofort negativ.",["Heute wird nichts gehen.","Müdigkeit wahrnehmen. Qualität des nächsten Schrittes prüfen.","Ich bin trotzdem topfit."],1,"Die Aussage bleibt realistisch und richtet sich auf beobachtbares Verhalten."],
["Du willst mehrere Dinge gleichzeitig korrigieren.",["Alles gleichzeitig besser machen.","Eine Korrektur wählen. Diese sauber umsetzen.","Mehr nachdenken."],1,"Ein einzelner Cue reduziert unnötige kognitive Last."],
["Eine andere Person wirkt sehr souverän.",["Ich muss genauso wirken.","Bei meiner Aufgabe bleiben. Nächste Handlung vorbereiten.","Die Person ist bestimmt besser."],1,"Die Aufmerksamkeit wird vom Vergleich auf den eigenen Prozess zurückgeführt."],
["Du wartest auf eine wichtige Rückmeldung.",["Ich muss wissen, wie es ausgeht.","Ungewissheit stehen lassen. Aufmerksamkeit zur aktuellen Aufgabe.","Bestimmt wird alles gut."],1,"Die Formulierung verlangt keine Sicherheit, bevor du handlungsfähig bist."],
["Du merkst, dass du dich innerlich stark bewertest.",["Ich bin heute schlecht.","Bewertung bemerken. Relevante Information auswählen. Weiterarbeiten.","Ich darf mich nicht bewerten."],1,"Die Bewertung wird bemerkt, ohne mit ihr zu kämpfen."],
["Vor einer schwierigen Phase steigt deine Anspannung.",["Ich muss entspannter sein.","Spannung prüfen. Atmung ordnen. Aufgabe klar halten.","Bloß keine Nervosität."],1,"Nicht jede Spannung muss verschwinden; entscheidend ist die Steuerbarkeit."],
["Du hast gerade etwas sehr gut gemacht.",["Jetzt muss alles so weitergehen.","Erfolg registrieren. Gleichen Ablauf erneut vorbereiten.","Heute kann nichts schiefgehen."],1,"Auch nach Erfolg bleibt der Fokus auf dem wiederholbaren Prozess."],
["Du bemerkst einen aufdringlichen negativen Gedanken.",["Weg damit.","Gedanken bemerken. Nicht beantworten. Aufmerksamkeit zurückführen.","Ich brauche einen positiven Gedanken."],1,"Gedanken müssen nicht ersetzt werden, um die Aufmerksamkeit neu auszurichten."],
["Du willst eine Aufgabe unbedingt perfekt lösen.",["Keinen Fehler machen.","Qualität anstreben. Nächsten Schritt vollständig ausführen.","Perfektion ist Pflicht."],1,"Der Cue hält den Qualitätsanspruch, ohne Fehlervermeidung zum Hauptziel zu machen."],
["Du bist nach einer Unterbrechung gedanklich nicht mehr bei der Sache.",["Ich habe den Faden verloren.","Orientieren. Einen Anker wählen. Wieder einsteigen.","Sofort wieder voll konzentrieren."],1,"Ein konkreter Wiedereinstieg ist steuerbarer als die Forderung nach maximaler Konzentration."],
["Eine Aufgabe dauert länger als erwartet.",["Das müsste längst fertig sein.","Tempo akzeptieren. Nächsten Abschnitt sauber bearbeiten.","Ich muss schneller werden."],1,"Die Formulierung verhindert, dass Zeitbewertung die aktuelle Handlung verdrängt."],
["Du spürst Unsicherheit, obwohl du vorbereitet bist.",["Ich dürfte nicht unsicher sein.","Unsicherheit zulassen. Vorbereitung nutzen. Beginnen.","Ich bin hundertprozentig sicher."],1,"Handlungsfähigkeit verlangt keine vollständige innere Sicherheit."]],
cues:[
["Du wirst hektisch.",["SCHNELLER","RHYTHMUS","NICHT NERVÖS"],1,"„Rhythmus“ ist kurz und unmittelbar handlungsbezogen."],
["Du verlierst dich in mehreren Gedanken.",["EINS","DENK NICHT","ALLES KONTROLLIEREN"],0,"„Eins“ reduziert auf den nächsten relevanten Schritt."],
["Die Körperspannung wird unnötig hoch.",["LOCKER","KEIN FEHLER","MEHR DRUCK"],0,"Der Cue lenkt auf den veränderbaren körperlichen Zustand."],
["Die Aufmerksamkeit wandert zum Ergebnis.",["JETZT","GEWINNEN","HOFFEN"],0,"„Jetzt“ führt die Aufmerksamkeit in die Gegenwart zurück."],
["Du denkst zu viel über die Technik nach.",["EINFACH","ANALYSIEREN","PERFEKT"],0,"„Einfach“ kann die Aufmerksamkeit von übermäßiger Kontrolle zurück zur Ausführung führen."],
["Du wirst passiv und zögerlich.",["ENTSCHLOSSEN","VORSICHT","ABWARTEN"],0,"„Entschlossen“ beschreibt die gewünschte Handlungsqualität."],
["Du verlierst deine aufrechte Haltung.",["AUFRICHTEN","NICHT SACKEN","KÄMPFEN"],0,"Der Cue benennt direkt die gewünschte Veränderung."],
["Dein Ablauf wird unruhig.",["RUHE","KEIN STRESS","MEHR"],0,"„Ruhe“ ist ein knapper Zustands-Cue ohne Negation."],
["Du möchtest den nächsten Schritt zu früh erzwingen.",["GEDULD","SOFORT","DRUCK"],0,"„Geduld“ schützt den Ablauf vor unnötigem Vorwegnehmen."],
["Du brauchst eine klare Ausrichtung.",["ZIEL","NICHT ABLENKEN","HOFFEN"],0,"„Ziel“ richtet Aufmerksamkeit knapp auf den relevanten Bezugspunkt."],
["Du sollst eine Bewegung flüssig halten.",["FLUSS","KONTROLLIEREN","NICHT STOCKEN"],0,"„Fluss“ beschreibt die gewünschte Qualität statt einen Fehler zu verbieten."],
["Nach einer Unterbrechung musst du neu beginnen.",["NEU","ÄRGERN","ZURÜCK"],0,"„Neu“ markiert einen klaren Neustart ohne Bewertung."],
["Du willst zu viele Details gleichzeitig steuern.",["KLAR","ALLES","DENKEN"],0,"„Klar“ unterstützt die Reduktion auf den wesentlichen Handlungsfokus."],
["Du brauchst einen aktiven ersten Schritt.",["START","WARTEN","NICHT ZÖGERN"],0,"„Start“ ist unmittelbar und positiv handlungsbezogen."],
["Du merkst unnötige Härte in der Ausführung.",["LEICHT","NICHT HART","MEHR KRAFT"],0,"„Leicht“ lenkt auf die gewünschte Bewegungsqualität."],
["Du verlierst den Takt.",["TAKT","SCHNELL","NICHT RAUSKOMMEN"],0,"„Takt“ stellt eine konkrete zeitliche Struktur wieder her."]],
scenes:[
["Bewegung","Stelle dir eine vertraute, technisch saubere Bewegung vor.","Erlebe den Ablauf aus deiner eigenen Perspektive."],
["Leistung","Stelle dir den Beginn einer anspruchsvollen Leistungssituation vor.","Erlebe Haltung, Blick und erste Handlung konkret."],
["Alltag","Stelle dir eine Aufgabe vor, bei der du leicht abschweifst.","Erlebe, wie du bei einem einzigen Schritt bleibst."],
["Training","Stelle dir den Beginn einer konzentrierten Trainingseinheit vor.","Erlebe den Übergang zur ersten sauberen Handlung."],
["Präzision","Stelle dir eine Aufgabe vor, bei der Genauigkeit wichtiger ist als Tempo.","Erlebe einen ruhigen, vollständigen Ablauf."],
["Dynamik","Stelle dir eine kraftvolle, dynamische Handlung vor.","Erlebe Vorbereitung, Impuls und kontrollierten Abschluss."],
["Lernen","Stelle dir eine noch nicht vollständig sichere Fertigkeit vor.","Erlebe eine bewusste, technisch geordnete Wiederholung."],
["Konzentration","Stelle dir eine längere Phase ungeteilter Aufmerksamkeit vor.","Erlebe, wie du nach kurzer Ablenkung ruhig zurückkehrst."],
["Entscheidung","Stelle dir eine Situation mit zwei sinnvollen Handlungsoptionen vor.","Erlebe Wahrnehmung, Entscheidung und entschlossene Ausführung."],
["Routine","Stelle dir einen vertrauten vorbereitenden Ablauf vor.","Erlebe jeden Schritt in seiner richtigen Reihenfolge."],
["Belastung","Stelle dir eine anspruchsvolle Aufgabe unter spürbarer Ermüdung vor.","Erlebe, wie die Ausführung trotz Belastung geordnet bleibt."],
["Neustart","Stelle dir den Wiederbeginn nach einer Unterbrechung vor.","Erlebe Orientierung, Fokus und den ersten klaren Schritt."]],
dis:["Ein unerwarteter Fehler unterbricht den Ablauf.","Ein störender Gedanke taucht vor der Handlung auf.","Du bemerkst plötzlich erhöhte Körperspannung.","Ein äußerer Reiz zieht die Aufmerksamkeit weg.","Der erste Versuch gelingt schlechter als erwartet.","Du wirst plötzlich hektischer als geplant.","Eine kurze Unterbrechung zerstört deinen Rhythmus.","Du bemerkst, dass du bereits an das Ergebnis denkst.","Ein unerwartetes Geräusch zieht den Fokus weg.","Die Bewegung fühlt sich zunächst ungewohnt an.","Du zweifelst für einen Moment an deiner Entscheidung.","Du willst die nächste Handlung zu früh erzwingen.","Du spürst Müdigkeit und bewertest sie negativ.","Ein guter Beginn erhöht plötzlich deinen Erwartungsdruck.","Du bemerkst, dass du mehrere Dinge gleichzeitig korrigieren willst."],
attention:[
["Spüre für einen Moment Atmung und Bodenkontakt.","Richte die Aufmerksamkeit anschließend auf ein neutrales Geräusch im Raum."],
["Nimm die Spannung in Händen und Kiefer wahr.","Wechsle danach zu einer Form oder Kontur vor dir."],
["Beobachte zwei Atemzüge, ohne sie zu verändern.","Richte den Fokus danach auf den gesamten Raum."],
["Nimm einen klaren Körperkontaktpunkt wahr.","Wechsle anschließend zu einem einzelnen visuellen Detail."],
["Bemerke deine momentane innere Aktivierung.","Richte die Aufmerksamkeit danach auf drei äußere Geräusche."]],
imageDetails:[
"Ergänze Haltung, Atmung, Muskelspannung und Bodenkontakt.",
"Spüre Stand, Schwerpunkt, Hände und den Rhythmus deiner Atmung.",
"Ergänze Temperatur, Körperspannung und die Position deiner Gelenke.",
"Nimm in der Vorstellung Druck unter den Füßen, Haltung und Atemtempo wahr.",
"Ergänze Bewegungsgefühl, Gleichgewicht und die Spannung, die du wirklich benötigst.",
"Spüre die Ausgangsposition so konkret, als würdest du sie gerade einnehmen."
],
regulations:[
"Atme einmal geordnet aus. Löse unnötige Spannung und richte die Aufmerksamkeit neu aus.",
"Bemerke die Reaktion. Wähle einen klaren Aufmerksamkeitsanker und setze den Ablauf fort.",
"Lass die Störung bestehen. Ordne Haltung und Atmung und kehre zur nächsten Handlung zurück.",
"Reduziere die Aufgabe auf einen steuerbaren Schritt. Führe genau diesen in der Vorstellung aus.",
"Nimm den Zustand wahr, ohne ihn zu bewerten. Stelle dann die nächste konkrete Handlung her."
],
precision:[
"Ergänze Tempo, Geräusche und Bewegungsgefühl.",
"Wiederhole den entscheidenden Abschnitt in realistischem Tempo.",
"Prüfe, ob Perspektive, Körpergefühl und Umgebung gleichzeitig vorhanden sind.",
"Stelle den Übergang zwischen Vorbereitung und Handlung besonders deutlich her.",
"Lass die Szene einmal ohne Kommentar vollständig ablaufen.",
"Ergänze genau das Detail, das die Handlung für dich realistisch macht."
],
acceptance:[
["Nimm leichte innere Unruhe wahr, ohne sie sofort verändern zu wollen.","Beschreibe sie innerlich knapp als Empfindung, nicht als Problem.","Richte die Aufmerksamkeit auf einen klaren nächsten Schritt."],
["Bemerke einen Moment von Unsicherheit.","Lass offen, ob die Unsicherheit gleich verschwindet.","Wähle trotzdem eine konkrete Handlung und stelle sie dir vor."],
["Nimm einen unangenehmen Gedanken wahr.","Lass ihn als Gedanken im Hintergrund bestehen.","Führe die Aufmerksamkeit zu Atmung, Körperkontakt und Aufgabe zurück."],
["Bemerke erhöhte Spannung im Körper.","Unterscheide notwendige Aktivierung von unnötiger Verkrampfung.","Löse nur den unnötigen Anteil und bleibe bei der Aufgabe."],
["Nimm Ungeduld wahr.","Lass den Wunsch nach sofortiger Veränderung kurz bestehen.","Arbeite den nächsten Abschnitt in deinem gewählten Tempo ab."]],
followups:[
["Welche Fortsetzung hält die Instruktion handlungsnah?","Zustand kontrollieren","Nächste Handlung benennen","Bleibe nicht beim inneren Zustand. Formuliere, was du jetzt konkret tun willst.","Gut. Verbinde die Instruktion mit genau einer unmittelbar folgenden Handlung."],
["Worauf sollte der nächste Fokus liegen?","Ergebnis absichern","Steuerbaren Prozess wählen","Formuliere keine Ergebnisgarantie. Kehre zu einem beeinflussbaren Teil des Ablaufs zurück.","Gut. Wähle einen beobachtbaren, steuerbaren Prozessschritt."],
["Wie wird der Cue wirksamer?","Mehr erklären","Kürzer und konkreter","Reduziere die Formulierung auf das, was die Handlung tatsächlich verändert.","Gut. Halte die Formulierung kurz genug, dass sie während einer Handlung verfügbar bleibt."],
["Was folgt nach einem störenden Gedanken?","Gedanken widerlegen","Aufmerksamkeit zurückführen","Du musst den Gedanken nicht gewinnen. Entscheidend ist, wohin du die Aufmerksamkeit danach richtest.","Gut. Lass den Gedanken bestehen und führe die Aufmerksamkeit bewusst zurück."],
["Wie bleibt die Formulierung realistisch?","Sicherheit behaupten","Handlung beschreiben","Vermeide Aussagen, die einen Zustand oder ein Ergebnis versprechen. Beschreibe Verhalten.","Gut. Die Formulierung verlangt keine Sicherheit, bevor du handeln kannst."],
["Was hilft bei zu vielen Korrekturen?","Alles erinnern","Einen Schwerpunkt wählen","Mehr Inhalt erhöht hier die Last. Wähle nur die wichtigste Korrektur.","Gut. Ein einzelner Schwerpunkt macht die Instruktion verfügbar und überprüfbar."]],
duration:{scan:75,breath:50,activation:55,focus:40,anchor:55,shift:55,imagery:95,coping:130,selftalk:80,cue:70,observe:60,senses:55,accept:65,relax:60}

};window.MIND.self.push(
["Mehrere kleine Fehler folgen schnell aufeinander.",["Heute geht alles schief.","Muster stoppen. Eine Information wählen. Nächsten Versuch ordnen.","Ich muss jetzt fehlerfrei sein."],1,"Die Instruktion reduziert die Situation auf einen verwertbaren nächsten Schritt.",2],
["Du bemerkst, dass du eine Entscheidung immer wieder überprüfst.",["Noch einmal alles durchdenken.","Entscheidung steht. Aufmerksamkeit zur Ausführung.","Hoffentlich war es richtig."],1,"Nach einer ausreichenden Entscheidung wird weiteres Grübeln nicht mit zusätzlicher Kontrolle verwechselt.",2],
["Eine Aufgabe fühlt sich plötzlich wichtiger an als sonst.",["Ich muss heute liefern.","Bedeutung wahrnehmen. Ablauf beibehalten. Ersten Schritt setzen.","Es ist eigentlich gar nicht wichtig."],1,"Die Bedeutung muss nicht kleingeredet werden; der Ablauf bleibt trotzdem steuerbar.",2],
["Du spürst starke Aktivierung, bist aber noch handlungsfähig.",["Ich muss komplett ruhig werden.","Energie nutzen. Atmung ordnen. Handlung klar halten.","Mehr Spannung hilft immer."],1,"Aktivierung wird reguliert, nicht pauschal beseitigt.",2],
["Nach Lob willst du die nächste Aufgabe besonders gut machen.",["Jetzt muss ich es beweisen.","Lob registrieren. Gleichen Prozess erneut ausführen.","Bloß nichts verändern."],1,"Der Fokus bleibt auf dem reproduzierbaren Ablauf statt auf der Bestätigung.",2],
["Du hast wenig Zeit und wirst gedanklich eng.",["Schneller denken.","Priorität wählen. Einen Schritt vollständig abschließen.","Keine Zeit verlieren."],1,"Zeitdruck wird durch Priorisierung beantwortet, nicht durch zusätzliche innere Hektik.",3],
["Ein unangenehmes Körpergefühl zieht immer wieder Aufmerksamkeit an.",["Das Gefühl muss weg.","Gefühl bemerken. Relevanz prüfen. Fokus bewusst zurückführen.","Ignorieren."],1,"Das Empfinden darf vorhanden sein, ohne automatisch die Aufgabe zu bestimmen.",3],
["Du hast eine gute Vorbereitung, fühlst dich aber nicht bereit.",["Ich sollte mich bereit fühlen.","Vorbereitung ist erfolgt. Ersten Schritt beginnen.","Noch warten, bis es passt."],1,"Handlungsbereitschaft wird nicht von einem perfekten inneren Zustand abhängig gemacht.",3],
["Du bemerkst nach einem Erfolg Übermut.",["Heute kann ich alles.","Erfolg registrieren. Anforderungen neu lesen. Gleichen Standard halten.","Ich muss mich bremsen."],1,"Die Instruktion stabilisiert Aufmerksamkeit, ohne Erfolg abzuwerten.",3],
["Eine Aufgabe erzeugt gleichzeitig Vorfreude und Nervosität.",["Ich muss mich für einen Zustand entscheiden.","Beides darf da sein. Haltung ordnen. Aufgabe beginnen.","Nervosität ist schlecht."],1,"Gemischte Zustände müssen nicht aufgelöst werden, bevor Handlung möglich ist.",3],
["Du weißt nicht, ob deine aktuelle Strategie funktionieren wird.",["Ich brauche Gewissheit.","Strategie sauber ausführen. Rückmeldung danach nutzen.","Einfach positiv denken."],1,"Unsicherheit wird durch einen überprüfbaren Prozess beantwortet.",4],
["Du bemerkst, dass du dich an einer früheren schlechten Erfahrung orientierst.",["Das passiert bestimmt wieder.","Erinnerung bemerken. Aktuelle Informationen prüfen. Jetzt handeln.","Vergangenheit vergessen."],1,"Vergangenheit wird weder verleugnet noch zur Vorhersage gemacht.",4],
["Du hast mehrere plausible Handlungsoptionen und keine ist sicher.",["Die perfekte Option finden.","Kriterien wählen. Entscheiden. Entscheidung ausführen.","Lieber nichts riskieren."],1,"Gute Entscheidungen benötigen nicht immer vollständige Sicherheit.",4],
["Du willst während der Ausführung kontrollieren, ob du gut genug bist.",["Ständig prüfen.","Ausführen. Bewertung bis zum geeigneten Zeitpunkt verschieben.","Gar nicht mehr bewerten."],1,"Ausführung und Bewertung werden zeitlich getrennt, statt gleichzeitig um Aufmerksamkeit zu konkurrieren.",4]
);
window.MIND.cues.push(
["Du grübelst nach einer bereits getroffenen Entscheidung.",["WEITER","NOCHMAL PRÜFEN","SICHER"],0,"„Weiter“ beendet die zusätzliche Entscheidungsschleife und führt zur Ausführung.",2],
["Du brauchst nach einer Ablenkung einen klaren Wiedereinstieg.",["HIER","NICHT ABLENKEN","VOLLER FOKUS"],0,"„Hier“ markiert den aktuellen Bezugspunkt ohne Forderung nach einem perfekten Zustand.",2],
["Du kontrollierst eine automatisierte Bewegung zu stark.",["LAUFEN LASSEN","MEHR DENKEN","PERFEKT"],0,"Der Cue reduziert bewusste Mikrokontrolle und lässt den vorbereiteten Ablauf zu.",2],
["Du bist zu vorsichtig und verlierst Handlungsklarheit.",["KLAR","KEIN RISIKO","ABWARTEN"],0,"„Klar“ richtet auf eine eindeutige Handlung statt auf Vermeidung.",2],
["Du brauchst nach einem Fehler sofort einen neuen Bezugspunkt.",["NÄCHSTE","WARUM","FEHLERFREI"],0,"„Nächste“ verschiebt Aufmerksamkeit von der Bewertung zur folgenden Handlung.",2],
["Du wirst unter Zeitdruck oberflächlich.",["SAUBER","SCHNELLER","PANIK"],0,"„Sauber“ schützt die wesentliche Handlungsqualität trotz knapper Zeit.",3],
["Du spürst hohe Aktivierung und willst sie sinnvoll nutzen.",["KANALISIEREN","WEG DAMIT","MEHR"],0,"„Kanalisieren“ behandelt Aktivierung als Energie, die auf die Aufgabe ausgerichtet wird.",3],
["Du musst eine unangenehme Empfindung nicht lösen, um fortzufahren.",["TROTZDEM","WEG","IGNORIEREN"],0,"„Trotzdem“ verbindet Akzeptanz mit Handlung, ohne das Empfinden zu verleugnen.",3],
["Du willst nach einem sehr guten Abschnitt den Standard halten.",["GLEICH","PERFEKT","ABSICHERN"],0,"„Gleich“ erinnert an den reproduzierbaren Ablauf statt an das Ergebnis.",3],
["Du hast mehrere plausible Optionen und musst dich festlegen.",["WÄHLEN","SICHER SEIN","WARTEN"],0,"„Wählen“ richtet auf die notwendige Entscheidung statt auf unerreichbare Gewissheit.",4],
["Du willst während der Handlung gleichzeitig bewerten.",["AUSFÜHREN","PRÜFEN","URTEILEN"],0,"„Ausführen“ trennt Handlung von späterer Bewertung.",4],
["Eine alte schlechte Erfahrung drängt sich in die aktuelle Aufgabe.",["JETZT","DAMALS","VERMEIDEN"],0,"„Jetzt“ bindet die Aufmerksamkeit an aktuelle Informationen statt an eine frühere Episode.",4]
);
